/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../App`; params?: Router.UnknownInputParams; } | { pathname: `/../main`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TopNav`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(library)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(search)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/player/now-playing`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../../vite.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../App`; params?: Router.UnknownOutputParams; } | { pathname: `/../main`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TopNav`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(library)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(search)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(settings)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/player/now-playing`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../../vite.config${`?${string}` | `#${string}` | ''}` | `/../App${`?${string}` | `#${string}` | ''}` | `/../main${`?${string}` | `#${string}` | ''}` | `/../components/TopNav${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(library)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(search)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(settings)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/player/now-playing${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../App`; params?: Router.UnknownInputParams; } | { pathname: `/../main`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TopNav`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(library)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(search)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(settings)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/player/now-playing`; params?: Router.UnknownInputParams; };
    }
  }
}
